### ISSUE TITLE
POSTCSS: failed to transform "assets/main/bundle.min.css"

### ISSUE THREAD

**Issue by Mecanik** [razonyang/hugo-theme-bootstrap-skeleton#18]
Hi,

Trying to deploy latest version on CF Pages, however it fails with: `Error: Error building site: POSTCSS: failed to transform "assets/main/bundle.min.css" (text/css): SyntaxError: Unexpected token ] in JSON at position 95`

Complete build log:

```
.......
2023-01-25T05:42:01.626552Z	Success: Finished cloning repository files
2023-01-25T05:42:02.377468Z	Installing dependencies
2023-01-25T05:42:02.389335Z	Python version set to 2.7
2023-01-25T05:42:05.966623Z	Downloading and installing node v16.13.2...
2023-01-25T05:42:06.420087Z	Downloading https://nodejs.org/dist/v16.13.2/node-v16.13.2-linux-x64.tar.xz...
2023-01-25T05:42:06.838438Z	Computing checksum with sha256sum
2023-01-25T05:42:06.965865Z	Checksums matched!
2023-01-25T05:42:11.29325Z	Now using node v16.13.2 (npm v8.1.2)
2023-01-25T05:42:11.709604Z	Started restoring cached build plugins
2023-01-25T05:42:11.723894Z	Finished restoring cached build plugins
2023-01-25T05:42:12.247231Z	Attempting ruby version 2.7.1, read from environment
2023-01-25T05:42:15.978588Z	Using ruby version 2.7.1
2023-01-25T05:42:16.352566Z	Using PHP version 5.6
2023-01-25T05:42:16.520341Z	5.2 is already installed.
2023-01-25T05:42:16.549973Z	Using Swift version 5.2
2023-01-25T05:42:16.550521Z	Started restoring cached node modules
2023-01-25T05:42:16.56905Z	Finished restoring cached node modules
2023-01-25T05:42:17.053726Z	Installing NPM modules using NPM version 8.1.2
2023-01-25T05:42:35.56786Z	
2023-01-25T05:42:35.568212Z	added 480 packages, and audited 481 packages in 18s
2023-01-25T05:42:35.56837Z	
2023-01-25T05:42:35.568511Z	47 packages are looking for funding
2023-01-25T05:42:35.568625Z	  run `npm fund` for details
2023-01-25T05:42:35.570321Z	
2023-01-25T05:42:35.570566Z	found 0 vulnerabilities
2023-01-25T05:42:35.585841Z	NPM modules installed
2023-01-25T05:42:36.136716Z	Installing Hugo 0.106.0
2023-01-25T05:42:37.498208Z	hugo v0.106.0-e08ce30fe4779e7d8a8395d7021314b915648cb4+extended linux/amd64 BuildDate=2022-11-17T18:33:40Z VendorInfo=gohugoio
2023-01-25T05:42:37.503527Z	Started restoring cached go cache
2023-01-25T05:42:37.526693Z	Finished restoring cached go cache
2023-01-25T05:42:37.527573Z	Installing Go version 1.18.1
2023-01-25T05:42:45.611424Z	
2023-01-25T05:42:45.627776Z	unset GOOS;
2023-01-25T05:42:45.643574Z	unset GOARCH;
2023-01-25T05:42:45.643923Z	export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.18.1.linux.amd64';
2023-01-25T05:42:45.644134Z	export PATH="/opt/buildhome/.gimme_cache/versions/go1.18.1.linux.amd64/bin:${PATH}";
2023-01-25T05:42:45.644593Z	go version >&2;
2023-01-25T05:42:45.644758Z	
2023-01-25T05:42:45.650898Z	export GIMME_ENV="/opt/buildhome/.gimme_cache/env/go1.18.1.linux.amd64.env"
2023-01-25T05:42:45.664896Z	go version go1.18.1 linux/amd64
2023-01-25T05:42:45.668205Z	Installing missing commands
2023-01-25T05:42:45.668492Z	Verify run directory
2023-01-25T05:42:45.668691Z	Executing user command: hugo --minify
2023-01-25T05:42:47.716973Z	hugo: downloading modules …
2023-01-25T05:42:48.637348Z	hugo: collected modules in 2921 ms
2023-01-25T05:42:48.759106Z	Start building sites … 
2023-01-25T05:42:48.759392Z	hugo v0.106.0-e08ce30fe4779e7d8a8395d7021314b915648cb4+extended linux/amd64 BuildDate=2022-11-17T18:33:40Z VendorInfo=gohugoio
2023-01-25T05:42:52.45272Z	Error: Error building site: POSTCSS: failed to transform "assets/main/bundle.min.css" (text/css): SyntaxError: Unexpected token ] in JSON at position 95
2023-01-25T05:42:52.453007Z	    at JSON.parse (<anonymous>)
2023-01-25T05:42:52.453163Z	    at defaultExtractor (/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/razonyang/hugo-theme-bootstrap@v1.0.0-beta2/purgecss.config.js:11:22)
2023-01-25T05:42:52.453351Z	    at A (/opt/buildhome/repo/node_modules/purgecss/lib/purgecss.js:1:4142)
2023-01-25T05:42:52.453502Z	    at P.extractSelectorsFromFiles (/opt/buildhome/repo/node_modules/purgecss/lib/purgecss.js:1:6179)
2023-01-25T05:42:52.453628Z	    at async /opt/buildhome/repo/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:646
2023-01-25T05:42:52.453738Z	    at async LazyResult.runAsync (/opt/buildhome/repo/node_modules/postcss/lib/lazy-result.js:433:15)
2023-01-25T05:42:52.453844Z	    at async Promise.all (index 0)
2023-01-25T05:42:52.453948Z	Total in 6740 ms
2023-01-25T05:42:52.466502Z	Failed: build command exited with code: 255
2023-01-25T05:42:53.408444Z	Failed: an internal error occurred
```

It builds and runs just fine on WSL (Ubuntu). I also matched the same versions of hugo, node, etc.

Any idea what is happening?

**Comment by razonyang** [comment]
I think this issue comes from `hugo_stats.json` or `extra_stats.json`. You can output and check those files by `cat` command or something else during the CF deployment.

**Comment by Mecanik** [comment]
I don't think you can cat during CF deployment.

**Comment by razonyang** [comment]
Another clue is that emulate this in local, `hugo -e production --minify -b http://localhost:1313`.

**Comment by Mecanik** [comment]
> Another clue is that emulate this in local, `hugo -e production --minify -b http://localhost:1313`.

Yes, this works. Now checking.

**Comment by Mecanik** [comment]
All good, an extra "," was present in extra_stats.json.

Thank you!
